NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME        = "WEXLM"
ORG_URL         = "https://wexlm.github.io/"
ORG_LOGO        = "https://wexlm.github.io/assets/wexlm.png"
ORG_DBA         = "88 Colin P Kelly Jr St, San Francisco, CA 94107, USA"
ORG_DESCRIPTION = "Smart Contract Utilities for Assets on Stellar Blockchain (XLM-based)"
ORG_OFFICIAL_EMAIL = "wexlm@proton.me"

[[CURRENCIES]]
code              = "WEXLM"
issuer            = "GBYGO5OUQW7SNTB3HKDACAYO7VCWGJTBBPQNMATJ7H6KS62V4USDU4WV"
name              = "WEXLM"
status            = "live"
anchor_asset_type = "crypto"
image             = "https://wexlm.github.io/assets/wexlm.png"
conditions        = "Fixed 1 000 000 000 WEXLM supply. Issuer key will locked."
desc              = "WEXLM is a trusted leader in innovative financial solutions, dedicated to providing secure, reliable, and efficient services that meet our customers' needs. Our commitment to transparency and excellence ensures you can confidently partner with us for your financial success. WEXLM is a technical token designed to facilitate secure and efficient transactions within the WEXLM ecosystem. It serves as the primary digital asset for powering decentralized applications, enabling fast, low-cost transfers, and supporting the platform's infrastructure for scalable blockchain solutions."
fixed_number      = 1000000000
display_decimals  = 7
